[pytest]
testpaths = tests
addopts = -W error::RuntimeWarning -W ignore::urllib3.exceptions.NotOpenSSLWarning --disable-warnings
filterwarnings =
    error::RuntimeWarning
    ignore::urllib3.exceptions.NotOpenSSLWarning
    ignore:The `sift_py` module is deprecated:FutureWarning
